// <auto-generated />
namespace food_tracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edit_foreignkey_data_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_foreignkey_data_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201708121735190_edit_foreignkey_data_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
