// <auto-generated />
namespace food_tracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_amount_to_item : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_amount_to_item));
        
        string IMigrationMetadata.Id
        {
            get { return "201708221024467_add_amount_to_item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
